

<<<<<<< HEAD
baseurl: "http://localhost:4000"
=======
baseurl: "http://mahafuzur.github.io/airspace/"
>>>>>>> origin/gh-pages
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
